### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by php4fan** [wu4f/ropsten_faucet#1]
I clicked here:
![image](https://user-images.githubusercontent.com/13969584/158027587-203f18d2-3f3a-4268-872a-12f863ad1ec2.png)

I signed in with Google:
![image](https://user-images.githubusercontent.com/13969584/158027640-a2e87cbc-a6fc-4644-9a6a-bc9c25ad3dbd.png)

I entered the address and clicked to get ETH:
![image](https://user-images.githubusercontent.com/13969584/158027671-70c7fc48-6f6c-4aa0-9505-6d06f44bd983.png)

And I got this:
![image](https://user-images.githubusercontent.com/13969584/158027686-2958599a-3a3b-4ff1-9b7d-4b276377a7dc.png)

**Is this supposed to be an error message?** Because it doesn't look like one at all.

It says:
> Faucet is rate-limited based on e-mail, IP, and wallet addresses. ETH is not sent to addresses with large balances.

My reaction to that is "**Ok, so where do I click to proceed?**". Or maybe you have already sent the Eth? No, I didn't get it.

I do not meet any of those criteria. It's my first request by email, IP and wallet address and I have a balance of zero. 

So, if that _is_ indeed supposed to be an error message, telling me that I am not being given the ETH because of those reasons, then first of all it's poorly designed; secondly it's vague (which one is it?), and most important of all, **it's broken** because none of those is the case and I didn't get the ETH.

**Comment by wu4f** [comment]
Looks like the transaction failed.  Will need to add better error handling

**Comment by wu4f** [comment]
Found the failed transaction and manually sent the wallet 5 ETH.  Looks like a bug in transaction handling.  Thanks for the heads up.

**Comment by php4fan** [comment]
Thanks. Shouldn't the issue remain open though?

**Comment by wu4f** [comment]
I believe it is fixed in this morning's commit

Wu
