### ISSUE TITLE
Need Instructions to deploy it for other testnets

### ISSUE THREAD

**Issue by IMPranshu** [wu4f/ropsten_faucet#2]

**Comment by IMPranshu** [comment]
Hello developer. Can you please provide some instructions of it's working and how to get up and running it on my own server?

**Comment by wu4f** [comment]
An installation script for Ubuntu 20.04 with nginx is at install.sh in the
repository.  It is similar to this codelab.

https://codelabs.cs.pdx.edu/labs/C04.1g_nginx_compute_gb/index.html?index=..%2F..cs430#0

Wu

**Comment by wu4f** [comment]
https://github.com/wu4f/ropsten_faucet/blob/main/install.sh

**Comment by IMPranshu** [comment]
I have gone through the above. Can u please tell me how it is actually working? Because in the internet they are using an API to make faucet website and you are not using any API to make faucet and hence you are able to give high amount of faucet ethers and I want to do that for other networks also if possible and also I would like it to take as a side project for myself. I am a student and beginner in thia field too so it would be grateful for me if you help me with the resources that will be helpful to get this done

**Comment by wu4f** [comment]
You need to be mining ETH in order to be able to set up a faucet.  Once you
have done so, you configure the config.py with the private key of the
wallet that contains the ETH, your Google OAuth Client ID and secret
credentials, and a URL to an Infura node.

Wu

**Comment by IMPranshu** [comment]
Ok, now I get it. So you are first setting up the mining machine in the cloud and then linking the faucet with the signing method. Cool
